# ── Imagen base quiero usar una imagen ya hecha que tiene Node.js 20 instalado ────────────────────────

FROM node:20-slim

# Dependencias del sistema necesarias para Puppeteer/Chrome
# Instalar paquetes Linux

RUN apt-get update && apt-get install -y \
    chromium \
    libatk-bridge2.0-0 \
    libdrm2 \
    libxkbcommon0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxrandr2 \
    libgbm1 \
    libasound2 \
    fonts-liberation \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Decirle a Puppeteer que use el Chromium del sistema (no descarga el suyo)
# estas son la variables de entorno 
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

#esta es la caropeta de trabajo  osea que todo se va ejecutar aqui adentro 
WORKDIR /app

# Instala dependencias primero 
# aqui instala todas las dependencias  expres  prisma  ts 
#se copia el packjson primero 
COPY package*.json ./
RUN npm install

# Genera el cliente de Prisma
COPY prisma ./prisma
COPY prisma.config.ts ./
RUN npx prisma generate

# Copia el resto del código
#controllers  models  services  utils etcc osea todo el codigo
COPY . .

#puerto de entrada
EXPOSE 3000

# Entrypoint: migra y arranca con hot reload
#esto es que ejecutar cuando se inicia el contenedor en este caso construye la imagen crea contenedor y lo arranca 
CMD npx prisma db push && \
    npx ts-node-dev -r dotenv/config --respawn --transpile-only src/index.ts